### ISSUE TITLE
trying to convert .yml:  ndefined local variable or method `col' for main

### ISSUE THREAD

**Issue by Sergepetroff** [zph/moresql#13]
Traceback (most recent call last):
        5: from ./bin/convert_config_from_mosql_to_moresql:74:in `<main>'
        4: from ./bin/convert_config_from_mosql_to_moresql:74:in `each_with_object'
        3: from ./bin/convert_config_from_mosql_to_moresql:74:in `each'
        2: from ./bin/convert_config_from_mosql_to_moresql:78:in `block in <main>'
        1: from ./bin/convert_config_from_mosql_to_moresql:78:in `each'
./bin/convert_config_from_mosql_to_moresql:81:in `block (2 levels) in <main>': undefined local variable or method `col' for main:Object (NameError)
Did you mean?  cols

**Comment by zph** [comment]
Hi @Sergepetroff , I'm sorry to see that the script failed for you.

I'm removing it because it was out of date. Please see the `examples/moresql.json` file and new README section for helping new users get configured.

If you have questions about doing that manual conversion, please ask and I'll try to assist.
